=== ministryofjustice/hmpps-digital-prison-reporting-data-product-definitions-schema/schema/data-product-definition-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/ministryofjustice/hmpps-digital-prison-reporting-data-product-definitions-schema/483172c2c31b8cf051e428aa43db927d2c73b370/schema/data-product-definition-schema.json",
  "title": "Data Product Definition Schema",
  "type": "object",
  "required": ["id", "name", "metadata", "inputPorts", "outputPorts", "policy"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "scheduled": {
      "type": "boolean"
    },
    "metadata": {
      "$ref": "#/definitions/metadata"
    },
    "inputPorts": {
      "type": "array",
      "items": {
        "$ref": "inputPorts.json"
      }
    },
    "outputPorts": {
      "type": "array",
      "items": {
        "$ref": "outputPorts.json"
      }
    },
    "policy": {
      "type": "array",
      "items": {
        "$ref": "policy.json"
      }
    }
  },
  "additionalProperties": false,
  "definitions": {
    "metadata": {
      "type": "object",
      "required": ["version"],
      "properties": {
        "author": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        },
        "tags": {
          "$ref": "#/definitions/tags"
        }
      },
      "additionalProperties": false
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== ministryofjustice/hmpps-digital-prison-reporting-data-product-definitions-schema/schema/test-dpd.json
{
  "$schema": "https://raw.githubusercontent.com/ministryofjustice/hmpps-digital-prison-reporting-data-product-definitions-schema/c4a177ab68836c869f7779d3f3fef366e649d530/schema/data-product-definition-schema.json",
  "id": "test-id",
  "name": "some-name-here",
  "description": "a description",
  "metadata": {
    "version": "1.0.0",
    "tags": ["a tag"]
  },
  "inputPorts": [
    {
      "metadata": {
        "version": "1.0.0"
      },
      "datasource": [
        {
          "id": "somesource",
          "name": "SOMESOURCE",
          "database": "A_DATABASE",
          "catalog": "acatalog"
        }
      ],
      "dataset": [
        {
          "id": "id-123",
          "name": "Some dataset name",
          "description": "A dataset description",
          "datasource": "nomis",
          "query": "dataset_base_ AS (SELECT COL1 FROM FOO), dataset_ AS (SELECT COL2 FROM bar)",
          "parameters": [
            {
              "index": 0,
              "name": "some_name",
              "filterType": "autocomplete",
              "referenceType": "existingtype",
              "reportFieldType": "string",
              "display": "Display name",
              "description": "",
              "mandatory": "true"
            }
          ],
          "schema": {
            "field": [
              {
                "index": 0,
                "name": "field_1",
                "type": "string",
                "display": "Field 1",
                "legacyId": "asd.123",
                "legacySqlClass": "column"
              },
              {
                "index": 0,
                "name": "field_2",
                "type": "string",
                "display": "Field 2",
                "legacyId": "asd.45",
                "legacySqlClass": "column"
              },
              {
                "index": 0,
                "name": "field_3",
                "type": "string",
                "display": "Field 3",
                "legacyId": "asd.6573",
                "legacySqlClass": "column"
              }
            ]
          }
        }
      ]
    }
  ],
  "outputPorts": [
    {
      "metadata": {
        "version": "1.0.0"
      },
      "report": [
        {
          "id": "12356.AA",
          "name": "Report name goes here - this will be displayed",
          "classification": "OFFICIAL",
          "version": "1.0.0",
          "render": "HTML",
          "dataset": "1122344/AA11",
          "feature": [
            {
              "type": "print"
            }
          ],
          "specification": {
            "template": "list",
            "field": [
              {
                "name": "$ref:COL1",
                "display": "Col display name",
                "formula": "",
                "visible": "true",
                "sortable": true,
                "defaultsort": true
              },
              {
                "name": "$ref:COL2",
                "display": "Col 2 display name",
                "formula": "",
                "visible": "true",
                "sortable": false,
                "defaultsort": false
              }
            ]
          }
        }
      ]
    }
  ],
  "policy": [
    {
      "metadata": {
        "version": "1.0.0"
      },
      "id": "access",
      "description": "",
      "name": "",
      "type": "access",
      "rule": [
        {
          "effect": "permit",
          "condition": [
            {
              "match": ["${role}", "SOME_ROLE"]
            }
          ]
        }
      ]
    }
  ]
}
